version: 1.0.{build}
<<<<<<< HEAD
language: csharp
before_build:
- cmd: nuget restore
build:
  project: Seq.App.Asana.sln
  verbosity: minimal
artifacts:
- path: Seq.App.Asana\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 4y5H2ds9SkE9isuACLi/QKEC6X2FtKLlAdSLV8dqZFw2NXhVOzaRbGR4JPRzTb37
  on:
    branch: master