version: 0.0.{build}
branches:
  only:
  - master
clone_depth: 20
before_build:
- cmd: nuget restore
build:
  project: Seq.App.Asana.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: zqY071Ib5KpjccNp6876a0tXobCXnfYhfUxT3nD+Khga3zO4L+6gNt5RS7lD8He0kX2q3pJ43wVXgnOs2N9gNLzu3Dk22Trxs0xbMo9t9pI=
  on:
    branch: master