version: 0.0.{build}

branches:
  only:
  - master

clone_depth: 20

before_build:
- cmd: nuget restore

build:
  project: Seq.App.Asana.sln
  verbosity: minimal
 
after_build:
- cmd: nuget pack Seq.App.Asana\Seq.App.Asana.csproj -version "%APPVEYOR_BUILD_VERSION%"

artifacts:
- path: '*.nupkg'
  name: nuget-package
  
deploy:
- provider: NuGet
  api_key:
    secure: 0c6905d3-e9b1-4d34-afc7-5ae500c1f2b6
  artifact: nuget-package
  on:
    branch: master
