version: 0.0.{build}

branches:
  only:
  - master

clone_depth: 20

configuration: Release

before_build:
- cmd: nuget restore

build:
  project: Seq.App.Asana.sln
  verbosity: minimal
 
after_build:
<<<<<<< HEAD
- cmd: nuget pack Seq.App.Asana\Seq.App.Asana.csproj -version "%APPVEYOR_BUILD_VERSION%"
=======
- cmd: nuget pack Seq.App.Asana\Seq.App.Asana.csprj -version "%APPVEYOR_BUILD_VERSION%"
>>>>>>> 5b0ea44b76f25db6ec4ce0acf3f77ee5b8746cbe

artifacts:
- path: 'Seq.App.Asana/*.nupkg'
  name: nuget-package
  
deploy:
- provider: NuGet
  api_key:
    secure: c66d8d18-b7d5-4853-a1bf-e4101fa31eee
  artifact: nuget-package
  on:
    branch: master