version: 1.0.{build}
branches:
  only:
  - master
before_build:
- cmd: nuget restore
build:
  project: Seq.App.Asana.sln
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 4y5H2ds9SkE9isuACLi/QKEC6X2FtKLlAdSLV8dqZFw2NXhVOzaRbGR4JPRzTb37
  on:
    branch: master