version: 0.0.{build}
branches:
  only:
  - master
clone_depth: 20
before_build:
- cmd: nuget restore
build:
  project: Seq.App.Asana.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: c66d8d18-b7d5-4853-a1bf-e4101fa31eee
  on:
    branch: master